# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3773b2c5dcd645b656f79bf6e3feecea051e1c730bdd3ef1156e76685282a59fb2e7f6fe0619cb8e64d1ebe82d32918eb836b4725406212dd6aa7c429f05e0e1

test:
  secret_key_base: 8289107b6e80d0564970739a3758a50d51d7dca3555bd32bff0bfddf8dd4cccb8920477c855aa3042829bbb3a03aa224818cbae2fd9dbe12bb24766fe1bfb7a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
